# Generated by Django 5.0 on 2024-01-04 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categoires',
            new_name='Categories',
        ),
    ]
